name: Deploy to STaging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        id: deploy
        # Add your deployment steps here

      - name: Send Deployment Protection Rule
        id: send-protection-rule
        run: |
          # Replace with your actual URL and payload
          curl -X POST -H "Content-Type: application/json" -d '{"deployment_protection_rule": true}' https://your-custom-url.com
