name: My Manual Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: runs-on,runner=2cpu-linux-x64,run-id=${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a command
        run: echo "Hello, world!"
